In [63]:
import pandas as pd
data = pd.read_csv("./nyc_squirrels.csv")
print('Number of instances = %d' % (data.shape[0]))
print('Number of attributes = %d' % (data.shape[1]))
data.head()

Number of instances = 3023
Number of attributes = 36

,long,lat,unique_squirrel_id,hectare,shift,date,hectare_squirrel_number,age,primary_fur_color,highlight_fur_color,...,approaches,indifferent,runs_from,other_interactions,lat_long,zip_codes,community_districts,borough_boundaries,city_council_districts,police_precincts
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,NaN,NaN,NaN,...,False,False,False,NaN,POINT (-73.9561344937861 40.7940823884086),NaN,19,4,19,13
1,-73.957044,40.794851,37E-PM-1006-03,37E,PM,10062018,3,Adult,Gray,Cinnamon,...,False,False,True,me,POINT (-73.9570437717691 40.794850940803904),NaN,19,4,19,13
2,-73.976831,40.766718,2E-AM-1010-03,02E,AM,10102018,3,Adult,Cinnamon,NaN,...,False,True,False,NaN,POINT (-73.9768311751004 40.76671780725581),NaN,19,4,19,13
3,-73.975725,40.769703,5D-PM-1018-05,05D,PM,10182018,5,Juvenile,Gray,NaN,...,False,False,True,NaN,POINT (-73.9757249834141 40.7697032606755),NaN,19,4,19,13
4,-73.959313,40.797533,39B-AM-1018-01,39B,AM,10182018,1,NaN,NaN,NaN,...,False,False,False,NaN,POINT (-73.9593126695714 40.797533370163),NaN,19,4,19,13

In [64]:
import numpy as np
print('Number of rows before discarding duplicates = %d' % (data.shape[0]))
data = data.drop_duplicates(subset=['unique_squirrel_id'])
print('Number of rows after discarding duplicates = %d' % (data.shape[0]))
data.head()

Number of rows before discarding duplicates = 3023
Number of rows after discarding duplicates = 3018

,long,lat,unique_squirrel_id,hectare,shift,date,hectare_squirrel_number,age,primary_fur_color,highlight_fur_color,...,approaches,indifferent,runs_from,other_interactions,lat_long,zip_codes,community_districts,borough_boundaries,city_council_districts,police_precincts
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,NaN,NaN,NaN,...,False,False,False,NaN,POINT (-73.9561344937861 40.7940823884086),NaN,19,4,19,13
1,-73.957044,40.794851,37E-PM-1006-03,37E,PM,10062018,3,Adult,Gray,Cinnamon,...,False,False,True,me,POINT (-73.9570437717691 40.794850940803904),NaN,19,4,19,13
2,-73.976831,40.766718,2E-AM-1010-03,02E,AM,10102018,3,Adult,Cinnamon,NaN,...,False,True,False,NaN,POINT (-73.9768311751004 40.76671780725581),NaN,19,4,19,13
3,-73.975725,40.769703,5D-PM-1018-05,05D,PM,10182018,5,Juvenile,Gray,NaN,...,False,False,True,NaN,POINT (-73.9757249834141 40.7697032606755),NaN,19,4,19,13
4,-73.959313,40.797533,39B-AM-1018-01,39B,AM,10182018,1,NaN,NaN,NaN,...,False,False,False,NaN,POINT (-73.9593126695714 40.797533370163),NaN,19,4,19,13

In [65]:
print('Number of instances = %d' % data.shape[0])
print('Number of attributes = %d' % data.shape[1])

print('Number of missing values:')
for col in data.columns:
    print('\t%s: %d' % (col, data[col].isna().sum()))

Number of instances = 3018
Number of attributes = 36
Number of missing values:
	long: 0
	lat: 0
	unique_squirrel_id: 0
	hectare: 0
	shift: 0
	date: 0
	hectare_squirrel_number: 0
	age: 121
	primary_fur_color: 55
	highlight_fur_color: 1085
	combination_of_primary_and_highlight_color: 0
	color_notes: 2836
	location: 64
	above_ground_sighter_measurement: 114
	specific_location: 2543
	running: 0
	chasing: 0
	climbing: 0
	eating: 0
	foraging: 0
	other_activities: 2581
	kuks: 0
	quaas: 0
	moans: 0
	tail_flags: 0
	tail_twitches: 0
	approaches: 0
	indifferent: 0
	runs_from: 0
	other_interactions: 2779
	lat_long: 0
	zip_codes: 3009
	community_districts: 0
	borough_boundaries: 0
	city_council_districts: 0
	police_precincts: 0

In [66]:
columns_to_drop = ['specific_location', 'highlight_fur_color', 'specific_location','other_activities','other_interactions','zip_codes','color_notes']
data = data.drop(columns=columns_to_drop)

In [67]:
data

,long,lat,unique_squirrel_id,hectare,shift,date,hectare_squirrel_number,age,primary_fur_color,combination_of_primary_and_highlight_color,...,tail_flags,tail_twitches,approaches,indifferent,runs_from,lat_long,community_districts,borough_boundaries,city_council_districts,police_precincts
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,NaN,NaN,+,...,False,False,False,False,False,POINT (-73.9561344937861 40.7940823884086),19,4,19,13
1,-73.957044,40.794851,37E-PM-1006-03,37E,PM,10062018,3,Adult,Gray,Gray+Cinnamon,...,False,False,False,False,True,POINT (-73.9570437717691 40.794850940803904),19,4,19,13
2,-73.976831,40.766718,2E-AM-1010-03,02E,AM,10102018,3,Adult,Cinnamon,Cinnamon+,...,False,False,False,True,False,POINT (-73.9768311751004 40.76671780725581),19,4,19,13
3,-73.975725,40.769703,5D-PM-1018-05,05D,PM,10182018,5,Juvenile,Gray,Gray+,...,False,False,False,False,True,POINT (-73.9757249834141 40.7697032606755),19,4,19,13
4,-73.959313,40.797533,39B-AM-1018-01,39B,AM,10182018,1,NaN,NaN,+,...,False,False,False,False,False,POINT (-73.9593126695714 40.797533370163),19,4,19,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3018,-73.963943,40.790868,30B-AM-1007-04,30B,AM,10072018,4,Adult,Gray,Gray+,...,False,False,False,False,True,POINT (-73.9639431360458 40.7908677445466),19,4,19,13
3019,-73.970402,40.782560,19A-PM-1013-05,19A,PM,10132018,5,Adult,Gray,Gray+White,...,False,False,False,True,False,POINT (-73.9704015859639 40.7825600069973),19,4,19,13
3020,-73.966587,40.783678,22D-PM-1012-07,22D,PM,10122018,7,Adult,Gray,"Gray+Black, Cinnamon, White",...,False,False,False,True,False,POINT (-73.9665871993517 40.7836775064883),19,4,19,13
3021,-73.963994,40.789915,29B-PM-1010-02,29B,PM,10102018,2,NaN,Gray,"Gray+Cinnamon, White",...,False,False,False,True,False,POINT (-73.9639941227864 40.7899152327912),19,4,19,13
3022,-73.975479,40.769640,5E-PM-1012-01,05E,PM,10122018,1,Adult,Cinnamon,"Cinnamon+Gray, White",...,False,False,True,False,False,POINT (-73.9754794191553 40.7696404489025),19,4,19,13

In [68]:
print('Number of rows in original data = %d' % (data.shape[0]))

data = data.dropna()

print('Number of rows after discarding missing values = %d' % (data.shape[0]))

Number of rows in original data = 3018
Number of rows after discarding missing values = 2779

In [72]:
#data = data.reset_index()
data

,index,long,lat,unique_squirrel_id,hectare,shift,date,hectare_squirrel_number,age,primary_fur_color,...,tail_flags,tail_twitches,approaches,indifferent,runs_from,lat_long,community_districts,borough_boundaries,city_council_districts,police_precincts
0,1,-73.957044,40.794851,37E-PM-1006-03,37E,PM,10062018,3,Adult,Gray,...,False,False,False,False,True,POINT (-73.9570437717691 40.794850940803904),19,4,19,13
1,2,-73.976831,40.766718,2E-AM-1010-03,02E,AM,10102018,3,Adult,Cinnamon,...,False,False,False,True,False,POINT (-73.9768311751004 40.76671780725581),19,4,19,13
2,3,-73.975725,40.769703,5D-PM-1018-05,05D,PM,10182018,5,Juvenile,Gray,...,False,False,False,False,True,POINT (-73.9757249834141 40.7697032606755),19,4,19,13
3,5,-73.956570,40.790256,33H-AM-1019-02,33H,AM,10192018,2,Juvenile,Gray,...,False,False,False,False,False,POINT (-73.9565700386162 40.7902561000937),19,4,19,13
4,6,-73.971974,40.769305,6G-PM-1020-02,06G,PM,10202018,2,Adult,Gray,...,False,False,False,True,False,POINT (-73.9719735582476 40.7693045133578),19,4,19,13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2774,3017,-73.964544,40.781160,21F-PM-1018-02,21F,PM,10182018,2,Juvenile,Cinnamon,...,False,False,False,False,True,POINT (-73.9645437409662 40.7811599933331),19,4,19,13
2775,3018,-73.963943,40.790868,30B-AM-1007-04,30B,AM,10072018,4,Adult,Gray,...,False,False,False,False,True,POINT (-73.9639431360458 40.7908677445466),19,4,19,13
2776,3019,-73.970402,40.782560,19A-PM-1013-05,19A,PM,10132018,5,Adult,Gray,...,False,False,False,True,False,POINT (-73.9704015859639 40.7825600069973),19,4,19,13
2777,3020,-73.966587,40.783678,22D-PM-1012-07,22D,PM,10122018,7,Adult,Gray,...,False,False,False,True,False,POINT (-73.9665871993517 40.7836775064883),19,4,19,13
2778,3022,-73.975479,40.769640,5E-PM-1012-01,05E,PM,10122018,1,Adult,Cinnamon,...,False,False,True,False,False,POINT (-73.9754794191553 40.7696404489025),19,4,19,13